### ISSUE TITLE
Don't support utf-8 character in python source file.

### ISSUE THREAD

**Issue by lifubang** [cmorisse/ikp3db#9]
test3.py:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# 中文 --------------utf-8 characters-----------------
while 1:
	a=[]  
	s = input()
	
	if s != "":
		for x in s.split():  
		    a.append(int(x))  
		   
		print(sum(a))
	else:
		break
```
When debug, there will be some errors as follows:
```
Traceback (most recent call last):
  File "//usr/local/lib/python3.6/dist-packages/ikp3db.py", line 1864, in main
    ikpdb._runscript(mainpyfile)
  File "//usr/local/lib/python3.6/dist-packages/ikp3db.py", line 1414, in _runscript
    exec(statement, globals, locals)
  File "<string>", line 1, in <module>
  File "//usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 49: ordinal not in range(128)
```

The line 1400 in ikp3db.py should change to:
```
statement = "exec(compile(open('%s', encoding='utf-8').read(), '%s', 'exec'))" % (filename, filename,)
```
and it will be no error.

I have a pr #8 , please check it.

**Comment by cmorisse** [comment]
Hello,
Could you please retry using version 1.2.1 (from testpypi), I'm unable to reproduce the bug.
